AddReference "System.Core"
AddReference "System.Linq"

Imports Inventor
Imports System.IO
Imports System.Linq

Public Sub Main()
    'user feedback:
    Dim sw As New Stopwatch()
    sw.Start()
    Dim progressint As Integer = 1

    Dim percent As Double = Nothing

    Dim partlist As list(Of Document) = (From a As document In thisapplication.activedocument.allreferenceddocuments
                                         Where TypeOf a Is partdocument
                                         Select a).ToList()
    Dim totalnumreferenceddocuments As Integer = partlist.count
    For Each subdoc As document In partlist
        percent = (CDbl(progressint) / totalnumreferenceddocuments)
        progressint += 1
        If TypeOf subdoc Is PartDocument Then
            If Not subdoc.File.FullFileName.Contains("Content") Then 'skip CC and FACILITY files
                If Not subdoc.File.fullfilename.contains("FACILITY") Then
                    updatestatusbar(percent, "Processing: " & System.IO.Path.GetFileNameWithoutExtension(subdoc.File.fullfilename))
                    Dim oSketchBlocks As SketchBlockDefinitions = subdoc.ComponentDefinition.SketchBlockDefinitions
                    If oSketchBlocks.Count > 0 Then
                        SetorCreateCustomiProperty(subdoc, "SKETCHBLOCKPRESENT", True)
                        'iProperties.Value("Custom", "SKETCHBLOCKPRESENT") = True
                        SetorCreateCustomiProperty(subdoc, "SKETCHBLOCKCOUNT", oSketchBlocks.Count.ToString())
                        'iProperties.Value("Custom", "NUMSKETCHBLOCKS") = oSketchBlocks.Count
                    End If
                End If
            End If
            'no need to bother with sub assemblies since we are using the "AllReferencedDocuments" collection but we'll leave it here anyway.
        ElseIf TypeOf subdoc Is AssemblyDocument Then

        End If
    Next
    'If TypeOf ThisDoc.Document Is PartDocument Then
    '    SketchBlockCapture(ThisDoc.Document)
    'Else
    '    RunSketchBlockCapture(ThisDoc.Document)
    'End If
    ' MessageBox.Show("Done!")
    sw.Stop()
    Dim timeElapsed As Timespan = sw.elapsed
    messagebox.show("Processing took: " & String.Format("{0:00}:{1:00}:{2:00}.{3:00}",
                                                        timeElapsed.Hours,
                                                        timeElapsed.Minutes,
                                                        timeElapsed.Seconds,
                                                        timeElapsed.Milliseconds / 10))
    'MessageBox.Show("Operation took: " & GetTime(sw.Elapsed.Seconds) & " to complete.")
End Sub

Public Sub RunSketchBlockCapture(ByVal oDoc As Inventor.Document)
    Dim oAssy As inventor.AssemblyDocument
    Dim oSubDoc As Inventor.Document
    If oDoc.DocumentType = Inventor.DocumentTypeEnum.kAssemblyDocumentObject Then
        oAssy = CType(oDoc, AssemblyDocument)
        'AssemblyFeatureCount(oAssy)
        For Each oComp As document In oAssy.ReferencedDocuments
            'oSubDoc = CType(oComp.Definition.Document,Document)
            'MessageBox.Show(oSubDoc.File.FullFileName)
            If oComp.DocumentType = Inventor.DocumentTypeEnum.kAssemblyDocumentObject Then
                RunSketchBlockCapture(oComp)
            Else
                SketchBlockCapture(oComp)
            End If
        Next
    ElseIf oDoc.DocumentType = Inventor.DocumentTypeEnum.kPartDocumentObject Then
        SketchBlockCapture(oDoc)
    End If
End Sub

Sub SketchBlockCapture(ByVal oDoc As Inventor.Document)

    Try
        Dim SaveRequired As Boolean = False

        'uncomment for debugging purposes!
        'MessageBox.Show(DocName)
        If TypeOf oDoc Is PartDocument Then
            If Not oDoc.File.FullFileName.Contains("Content") And Not oDoc.File.fullfilename.contains("FACILITY") And Not oDoc.File.fullfilename.contains("Imported Components") Then 'skip CC and FACILITY files
                Dim PartDocName As String = System.IO.Path.GetFileNameWithoutExtension(oDoc.DisplayName) & ":1"
                Dim oSketchBlocks As SketchBlockDefinitions = oDoc.componentdefinition.SketchBlockDefinitions
                Dim oFeats As PartFeatures = oDoc.ComponentDefinition.Features
                Dim oParams As Parameters = oDoc.ComponentDefinition.Parameters
                Try
                    If oSketchBlocks.Count > 0 Then
                        iProperties.Value(PartDocName, "Custom", "SKETCHBLOCKPRESENT") = True
                        iProperties.Value(PartDocName, "Custom", "NUMSKETCHBLOCKS") = oSketchBlocks.Count
                    End If

                    'If Not iProperties.Value(PartDocName, "Custom", "FEATURECOUNT") = oFeats.Count Then 'or update it
                    '    iProperties.Value(PartDocName, "Custom", "FEATURECOUNT") = oFeats.Count
                    '    SaveRequired = True
                    'End If
                    ''MessageBox.Show("Feature Count for this part is: " & oFeats.Count, "FEATURECOUNT")
                    'If Not iProperties.Value(PartDocName, "Custom", "PARAMETERCOUNT") = oParams.Count Then 'or update it
                    '    iProperties.Value(PartDocName, "Custom", "PARAMETERCOUNT") = oParams.Count
                    '    SaveRequired = True
                    'End If
                    ''MessageBox.Show("Parameter Count for " & oDoc.File.fullfilename &" is: " & oParams.Count, "PARAMETERCOUNT")
                    'If SaveRequired Then
                    '    'oDoc.Save 'try to save the file.
                    'End If
                Catch
                    iProperties.Value(PartDocName, "Custom", "SKETCHBLOCKPRESENT") = True
                    iProperties.Value(PartDocName, "Custom", "NUMSKETCHBLOCKS") = oSketchBlocks.Count
                    'iProperties.Value(PartDocName, "Custom", "FEATURECOUNT") = oFeats.Count
                    'iProperties.Value(PartDocName, "Custom", "PARAMETERCOUNT") = oParams.Count
                    'oDoc.Save 'try to save the file.
                    Exit Sub
                End Try
            End If
        ElseIf TypeOf oDoc Is AssemblyDocument Then
            'If Not oDoc.File.FullFileName.Contains("Content") And Not oDoc.File.fullfilename.contains("FACILITY") And Not oDoc.File.fullfilename.contains("Imported Components") Then
            '    Dim DocName As String = System.IO.Path.GetFileNameWithoutExtension(oDoc.DisplayName) & ":1"
            '    Dim oFeats As Features = oDoc.ComponentDefinition.Features
            '    Dim Occs As ComponentOccurrences = oDoc.ComponentDefinition.Occurrences
            '    Dim oParams As Parameters = oDoc.ComponentDefinition.Parameters
            '    'Dim oConstraints as Constraints = oDoc.ComponentDefinition.Constraints
            '    Try
            '        If Not iProperties.Value(DocName, "Custom", "FEATURECOUNT") = oFeats.Count Then
            '            iProperties.Value(DocName, "Custom", "FEATURECOUNT") = oFeats.Count
            '            SaveRequired = True
            '        End If
            '        'MessageBox.Show("Feature Count for this assembly is: " & oFeats.Count, "FEATURECOUNT")
            '        If Not iProperties.Value(DocName, "Custom", "OCCURRENCECOUNT") = Occs.Count Then
            '            iProperties.Value(DocName, "Custom", "OCCURRENCECOUNT") = Occs.Count
            '            SaveRequired = True
            '        End If
            '        'MessageBox.Show("Occurrence Count for " & oDoc.File.fullfilename & " is: " & Occs.Count, "OCCURRENCECOUNT")
            '        If Not iProperties.Value(DocName, "Custom", "PARAMETERCOUNT") = oParams.Count Then
            '            iProperties.Value(DocName, "Custom", "PARAMETERCOUNT") = oParams.Count
            '            SaveRequired = True
            '        End If
            '        'MessageBox.Show("Parameter Count for this part is: " & oDoc.ComponentDefinition.Constraints.Count, "PARAMETERCOUNT")
            '        If Not iProperties.Value(DocName, "Custom", "CONSTRAINTCOUNT") = oDoc.ComponentDefinition.Constraints.Count Then
            '            iProperties.Value(DocName, "Custom", "CONSTRAINTCOUNT") = oDoc.ComponentDefinition.Constraints.Count
            '            SaveRequired = True
            '        End If
            '        'MessageBox.Show("Constraint Count for Assembly " & DocName & " is: " & oDoc.ComponentDefinition.Constraints.Count, "CONSTRAINTCOUNT")
            '        If SaveRequired Then
            '            'oDoc.Save 'try to save the file.
            '        End If
            '    Catch
            '        'creates any missing iProperties.
            '        iProperties.Value(DocName, "Custom", "FEATURECOUNT") = oFeats.Count
            '        iProperties.Value(DocName, "Custom", "OCCURRENCECOUNT") = Occs.Count
            '        iProperties.Value(DocName, "Custom", "PARAMETERCOUNT") = oParams.Count
            '        iProperties.Value(DocName, "Custom", "CONSTRAINTCOUNT") = oDoc.ComponentDefinition.Constraints.Count
            '        'oDoc.Save 'saves the assembly
            '        Exit Sub
            '    End Try
            'End If
        End If
    Catch ex As Exception
        'MessageBox.Show("The error is: " & ex.Message & VBCrlf & ex.StackTrace, oDoc.DisplayName)
    End Try

End Sub
Dim SaveRequired As Boolean = False
Sub PartFeatureCount(ByVal oDoc)
    Try
        If Not oDoc.File.FullFileName.Contains("Content") And Not oDoc.File.fullfilename.contains("FACILITY") And Not oDoc.File.fullfilename.contains("Imported Components") Then
            Dim oFeats As PartFeatures = oDoc.Document.ComponentDefinition.Features
            Dim oParams As Parameters = oDoc.Document.ComponentDefinition.Parameters
            Try
                'may need to save the file when we're done, hence the boolean check
                If Not iProperties.Value("Custom", "FEATURECOUNT") = oFeats.Count Then
                    iProperties.Value("Custom", "FEATURECOUNT") = oFeats.Count
                    SaveRequired = True
                End If
                'MessageBox.Show("Feature Count for this part is: " & oFeats.Count, "FEATURECOUNT")

                If Not iProperties.Value("Custom", "PARAMETERCOUNT") = oParams.Count Then
                    iProperties.Value("Custom", "PARAMETERCOUNT") = oParams.Count
                    SaveRequired = True
                End If
                'MessageBox.Show("Parameter Count for " & oDoc.Document.File.fullfilename &" is: " & oParams.Count, "PARAMETERCOUNT")
                If SaveRequired Then
                    'oDoc.Save 'try to save the file.
                End If
            Catch
                'definitely need to save the file!
                iProperties.Value("Custom", "FEATURECOUNT") = oFeats.Count
                iProperties.Value("Custom", "PARAMETERCOUNT") = oParams.Count
                'oDoc.Save 'try to save the file.
                'oDoc.Close 'try to close the file - on a vaulted file this will fire the check-in dialogue.
            End Try
        End If
    Catch ex As Exception
        MessageBox.Show("The error is: " & ex.Message & VBCrlf & ex.StackTrace)
    End Try

End Sub

Sub AssemblyFeatureCount(ByVal oDoc)
    Try
        Dim SaveRequired As Boolean = False
        'Dim DocName As String = oDoc.DisplayName
        If Not oDoc.File.FullFileName.Contains("Content") And Not oDoc.File.fullfilename.contains("FACILITY") And Not oDoc.File.fullfilename.contains("Imported Components") Then
            Dim oFeats As Features = oDoc.ComponentDefinition.Features
            Dim Occs As ComponentOccurrences = oDoc.ComponentDefinition.Occurrences
            Dim oParams As Parameters = oDoc.ComponentDefinition.Parameters
            'Dim oConstraints as Constraints = oDoc.ComponentDefinition.Constraints
            Try
                If Not iProperties.Value("Custom", "FEATURECOUNT") = oFeats.Count Then
                    iProperties.Value("Custom", "FEATURECOUNT") = oFeats.Count
                    SaveRequired = True
                End If
                'MessageBox.Show("Feature Count for this assembly is: " & oFeats.Count, "FEATURECOUNT")
                If Not iProperties.Value("Custom", "OCCURRENCECOUNT") = Occs.Count Then
                    iProperties.Value("Custom", "OCCURRENCECOUNT") = Occs.Count
                    SaveRequired = True
                End If
                'MessageBox.Show("Occurrence Count for " & oDoc.File.fullfilename & " is: " & Occs.Count, "OCCURRENCECOUNT")
                If Not iProperties.Value("Custom", "PARAMETERCOUNT") = oParams.Count Then
                    iProperties.Value("Custom", "PARAMETERCOUNT") = oParams.Count
                    SaveRequired = True
                End If
                'MessageBox.Show("Parameter Count for this part is: " & oDoc.ComponentDefinition.Constraints.Count, "PARAMETERCOUNT")
                If Not iProperties.Value("Custom", "CONSTRAINTCOUNT") = oDoc.ComponentDefinition.Constraints.Count Then
                    iProperties.Value("Custom", "CONSTRAINTCOUNT") = oDoc.ComponentDefinition.Constraints.Count
                    SaveRequired = True
                End If
                'MessageBox.Show("Constraint Count for Assembly " & DocName & " is: " & oDoc.ComponentDefinition.Constraints.Count, "CONSTRAINTCOUNT")
                If SaveRequired Then
                    'oDoc.Save 'try to save the file.
                End If
            Catch
                'creates any missing iProperties.
                iProperties.Value("Custom", "FEATURECOUNT") = oFeats.Count
                iProperties.Value("Custom", "OCCURRENCECOUNT") = Occs.Count
                iProperties.Value("Custom", "PARAMETERCOUNT") = oParams.Count
                iProperties.Value("Custom", "CONSTRAINTCOUNT") = oDoc.ComponentDefinition.Constraints.Count
                'oDoc.Save 'saves the assembly
                Exit Sub
            End Try
        End If
    Catch ex As Exception
        MessageBox.Show("The error is: " & ex.Message & VBCrlf & ex.StackTrace)
    End Try
End Sub


Sub updatestatusbar(ByVal message As String)
    thisApplication.statusbartext = message
End Sub

Sub updatestatusbar(ByVal percent As Double, ByVal message As String)
    ThisApplication.statusbartext = message + " (" & percent.ToString("P1") + ")"
End Sub

Public Function GetTime(Time As Integer) As String
    Dim Hrs As Integer  'number of hours   '
    Dim Min As Integer  'number of Minutes '
    Dim Sec As Integer  'number of Sec     '

    'Seconds'
    Sec = Time Mod 60

    'Minutes'
    Min = ((Time - Sec) / 60) Mod 60

    'Hours'
    Hrs = ((Time - (Sec + (Min * 60))) / 3600) Mod 60

    Return Format(Hrs, "00") & ":" & Format(Min, "00") & ":" & Format(Sec, "00")
End Function

'Sub Main()
'    For Each subdoc As Document In ThisApplication.ActiveDocument.AllReferencedDocuments
'        If TypeOf subdoc Is PartDocument Then
'            If Not subdoc.Document.File.FullFileName.Contains("Content") Then 'skip CC and FACILITY files
'                If Not subdoc.Document.File.fullfilename.contains("FACILITY") Then
'                    Dim oSketchBlocks As SketchBlockDefinitions = ThisDoc.Document.ComponentDefinition.SketchBlockDefinitions
'                    If oSketchBlocks.Count > 0 Then
'                        iProperties.Value("Custom", "SKETCHBLOCKPRESENT") = True
'                        iProperties.Value("Custom", "NUMSKETCHBLOCKS") = oSketchBlocks.Count
'                    End If
'                End If
'            End If
'            'no need to bother with sub assemblies since we are using the "AllReferencedDocuments" collection but we'll leave it here anyway.
'        ElseIf TypeOf subdoc Is AssemblyDocument Then

'        End If
'    Next
'End Sub
''' <summary>
''' This method should set or get any custom iProperty value
''' </summary>
''' <param name="Doc">the document to edit</param>
''' <param name="PropertyName">the iProperty name to retrieve or update</param>
''' <param name="PropertyValue">the optional value to assign - if empty we are retrieving a value</param>
''' <returns></returns>
Friend Shared Function SetorCreateCustomiProperty(ByVal Doc As Inventor.Document, ByVal PropertyName As String, Optional ByVal PropertyValue As Object = Nothing) As Object
    ' Get the custom property set. 
    Dim customPropSet As Inventor.PropertySet
    Dim customproperty As Object = Nothing

    customPropSet = Doc.PropertySets.Item("Inventor User Defined Properties")

    ' Get the existing property, if it exists. 
    Dim prop As Inventor.Property = Nothing
    Dim propExists As Boolean = True
    Try
        prop = customPropSet.Item(PropertyName)
    Catch ex As Exception
        propExists = False
    End Try
    If Not PropertyValue Is Nothing Then
        ' Check to see if the property was successfully obtained. 
        If Not propExists Then
            ' Failed to get the existing property so create a new one. 
            prop = customPropSet.Add(PropertyValue, PropertyName)
        Else
            ' Change the value of the existing property. 
            prop.Value = PropertyValue
        End If
    Else
        customproperty = prop.Value
    End If
    Return customproperty
End Function