imports System.Linq
Sub Main()
	If TypeOf ThisApplication.ActiveDocument Is AssemblyDocument Then
		Dim AssyDoc As AssemblyDocument = ThisApplication.ActiveDocument
		Dim AssyDef As AssemblyComponentDefinition = AssyDoc.ComponentDefinition
		
		Dim cutSketch As PlanarSketch = (From sk As PlanarSketch In AssyDef.Sketches
											Where sk.name.contains("cut")
											Select sk).FirstOrDefault()
		If Not cutSketch Is Nothing Then
			Dim cutProfile As Profile = cutSketch.Profiles.AddForSolid
			Dim extrudeDef As ExtrudeDefinition = AssyDef.Features.ExtrudeFeatures.CreateExtrudeDefinition(cutProfile, PartFeatureOperationEnum.kCutOperation)
			Dim cutPlane1 As WorkPlane = (From wp As WorkPlane In AssyDef.WorkPlanes
											Where wp.name.contains("1")
											Select wp).FirstOrDefault()
			Dim cutPlane2 As WorkPlane = (From wp As WorkPlane In AssyDef.WorkPlanes
											Where wp.name.contains("2")
											Select wp).FirstOrDefault()
			If Not cutPlane1 Is Nothing And Not cutPlane2 Is Nothing Then
				extrudeDef.SetFromToExtent(cutPlane1, True, cutPlane2, True)
			Else
				MessageBox.Show("couldn't find workplanes containing 1 & 2 in their names")
			End If
		Else
			MessageBox.Show("We couldn't find the right sketch! Exiting.")
			Exit Sub
		End If
	Else
		MessageBox.Show("NOt using an Assembly, Exiting!")
		Exit Sub
	End If
End Sub