Sub Main()
	Dim oDocument As drawingdocument = ThisApplication.ActiveDocument
	Dim oSheets As Sheets
	Dim oSheet As Sheet
	Dim DrawingNumber As String = String.empty
	Dim DrawingTitle As String = String.empty
	Dim DrawingPrefix As String = String.Empty
	Dim oPar As UserParameter

	For i = 1 To oDocument.Sheets.Count
		oDocument.Sheets(i).Activate
		oSheet = oDocument.Sheets(i)
		'MessageBox.Show(osheet.Name)
		Dim oTitleBlock As TitleBlock = oDocument.Sheets(i).TitleBlock
		For Each oTextBox As Inventor.TextBox In oTitleBlock.Definition.Sketch.TextBoxes
			' MessageBox.Show(otextbox.Text)
			If oTextBox.Text <> "" Then
				'*add further textboxes you want to check here:
				'** you will need to edit the titleblock in the Inventor UI and note down the textbox names to then add
				' them here.
				Select oTextBox.Text
					Case "<PART NUMBER>":
						DrawingNumber = oTitleBlock.GetResultText(oTextBox)
					Case "Drawing Prefix": 
						DrawingPrefix = oTitleBlock.GetResultText(oTextBox)
					Case "<TITLE>":
						DrawingTitle = oTitleBlock.GetResultText(oTextBox)
				End Select
			End If
		Next
		' If Not DrawingNumber = String.Empty And Not DrawingTitle = String.Empty Then ' DrawingPrefix = String.empty Then
			' MessageBox.Show("Filename will include: " & DrawingNumber & " & " & DrawingTitle)
			' PrintSheet(osheet, DrawingNumber, DrawingPrefix, singleSheet)
		' Else
			' MessageBox.Show("Either the Drawing Number or Prefix was missing on this sheet, Exiting!")
			' Exit Function
		' End If
	Next
End Sub

Function CheckTextBoxContents(byval textbox as Inventor.TextBox) as boolean

End Function

Function CompareTextToExpected(byval textBoxContents as string) as Boolean

End Function