Sub Main()
	Dim oDocument As drawingdocument = ThisApplication.ActiveDocument
	Dim oSheets As Sheets
	Dim oSheet As Sheet
	' Dim DrawingNumber As String = String.empty
	' Dim DrawingTitle As String = String.empty
	' Dim DrawingPrefix As String = String.Empty
	Dim oPar As UserParameter

	For i = 1 To oDocument.Sheets.Count
		oDocument.Sheets(i).Activate
		oSheet = oDocument.Sheets(i)
		'MessageBox.Show(osheet.Name)
		Dim oTitleBlock As TitleBlock = oDocument.Sheets(i).TitleBlock
		For Each oTextBox As Inventor.TextBox In oTitleBlock.Definition.Sketch.TextBoxes
			' MessageBox.Show(otextbox.Text)
			If oTextBox.Text <> "" Then
				CompareTextToExpected(oTextBox, oTitleBlock.GetResultText(oTextBox))
			End If
		Next
		' If Not DrawingNumber = String.Empty And Not DrawingTitle = String.Empty Then ' DrawingPrefix = String.empty Then
			' MessageBox.Show("Filename will include: " & DrawingNumber & " & " & DrawingTitle)
			' PrintSheet(osheet, DrawingNumber, DrawingPrefix, singleSheet)
		' Else
			' MessageBox.Show("Either the Drawing Number or Prefix was missing on this sheet, Exiting!")
			' Exit Function
		' End If
	Next
End Sub

Sub MarkTextBoxContentsAsIncorrect(byval textbox as Inventor.TextBox)
	
End Sub

Function CompareTextToExpected(byval textBox as Inventor.TextBox, byval textBoxContents as string) as Boolean
	select case textBox.Text
		case "Title" :
			if not textBoxContents = "your expected string" then MarkTextBoxContentsAsIncorrect(textBox)
		case "Part Number" :
			if not textBoxContents = "your expected string" then MarkTextBoxContentsAsIncorrect(textBox)
	end select
End Function