Sub Main()
	oDocument = ThisApplication.ActiveDocument
	Dim oSheets As Sheets
	Dim oSheet As Sheet
	' Dim DrawingNumber As String = String.empty
	' Dim DrawingTitle As String = String.empty
	' Dim DrawingPrefix As String = String.Empty
	Dim oPar As UserParameter

	For i = 1 To oDocument.Sheets.Count
		oDocument.Sheets(i).Activate
		oSheet = oDocument.Sheets(i)
		'MessageBox.Show(osheet.Name)
		Dim oTitleBlock As TitleBlock = oDocument.Sheets(i).TitleBlock
		For Each oTextBox As Inventor.TextBox In oTitleBlock.Definition.Sketch.TextBoxes
			' MessageBox.Show(otextbox.Text)
			If oTextBox.Text <> "" Then
				CompareTextToExpected(oTextBox, oTitleBlock.GetResultText(oTextBox))
			End If
		Next
	Next
End Sub

public oDocument As drawingdocument = nothing

Function CompareTextToExpected(byval textBox as Inventor.TextBox, byval textBoxContents as string) as Boolean
	select case textBox.Text
		case "Title" :
			if not textBoxContents = "your expected string" then MarkTextBoxContentsAsIncorrect(textBox, "Text doesn't match expected Title")
		case "Part Number" :
			if not textBoxContents = "your expected string" then MarkTextBoxContentsAsIncorrect(textBox, "Text doesn't match expected Part Number")
	end select
End Function

Sub MarkTextBoxContentsAsIncorrect(byval textbox as Inventor.TextBox, byval ErrorText as string)
	
End Sub

Sub CreateText (byval textlocation as point2d, byval QAText As String)

	Dim oSheet As Sheet
	Dim oDrawingView As DrawingView
	Dim oTG As TransientGeometry
	Dim oPoint As Point2d
	Dim TextPoint As Point2d
	Dim ViewWidth As Double
	Dim TextWidth As Double
	
	'Set the Drawing View based on the Index passed into the sub
	oSheet = oDrawingDoc.Sheets.Item(1)
	oDrawingView = oSheet.DrawingViews.Item(ViewNumber)
	oTG = ThisApplication.TransientGeometry
	
	TextPoint = oTG.CreatePoint2d(0, 0)
	
	
	Dim oGeneralNotes As GeneralNotes
	oGeneralNotes = oSheet.DrawingNotes.GeneralNotes
	
	'Randomly place the Text (oText is the string passed through the sub)
	Dim oGeneralNote As GeneralNote
	oGeneralNote = oGeneralNotes.AddFitted(oTG.CreatePoint2d(5, 5), oText)
	
	'Get the origin points of the View
	oPointx = oDrawingView.Position.x
	oPointy = oDrawingView.Position.y
	
	'Get the Lengths of the View and Text
	ViewWidth = oDrawingView.Width
	ViewHeight = oDrawingView.Height
	TextWidth = oGeneralNote.Width
	
	'This will Center the text width wise and place it at the OffsetDistance Vertically
	TextPoint.x = oPointx - TextWidth/2
	TextPoint.y = oPointy - ViewHeight + OffsetDistance
	
	'Set the TextPoint 
	oGeneralNote.Position = TextPoint

End Sub