Sub Main()
	oDocument = ThisApplication.ActiveDocument
	Dim oSheets As Sheets
	Dim oSheet As Sheet
	Dim oPar As UserParameter

	For i = 1 To oDocument.Sheets.Count
		oDocument.Sheets(i).Activate
		oSheet = oDocument.Sheets(i)
		Dim oTitleBlock As TitleBlock = oDocument.Sheets(i).TitleBlock
		For Each oTextBox As Inventor.TextBox In oTitleBlock.Definition.Sketch.TextBoxes
			If oTextBox.Text <> "" Then
				CompareTextToExpected(oTextBox, oTitleBlock.GetResultText(oTextBox))
			End If
		Next
	Next
End Sub

public oDocument As drawingdocument = nothing

Function CompareTextToExpected(byval textBox as Inventor.TextBox, byval textBoxContents as string) as Boolean
	select case textBox.Text
		case "Title" :
			if not textBoxContents = "your expected string" then MarkTextBoxContentsAsIncorrect(textBox, "Text doesn't match expected Title")
		case "Part Number" :
			if not textBoxContents = "your expected string" then MarkTextBoxContentsAsIncorrect(textBox, "Text doesn't match expected Part Number")
	end select
End Function

Sub MarkTextBoxContentsAsIncorrect(byval textbox as Inventor.TextBox, byval ErrorText as string)
	Call createText(textbox.location, ErrorText)
End Sub

Sub CreateText (byval textlocation as point2d, byval QAText As String)

	Dim oSheet As Sheet
	Dim oTG As TransientGeometry = ThisApplication.TransientGeometry
	Dim TextPoint As Point2d = oTG.CreatePoint2d(textLocation.X, textlocation.Y)
	
	'Set the Drawing View based on the Index passed into the sub
	oSheet = oDocument.Sheets.Item(1)
	
	Dim oGeneralNotes As GeneralNotes
	oGeneralNotes = oSheet.DrawingNotes.GeneralNotes
	
	Dim oGeneralNote As GeneralNote
	oGeneralNote = oGeneralNotes.AddFitted(TextPoint, QAText)

End Sub